id: P000390
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21849
  title: འགྲོ་བ་བཟང་མོ།
  author: ''
  volumes:
    857d77be10d94c16bfaaa630ab487cc9:
      image_group_id: I1KG23002
      title: Volume 1 of 'gro ba bzang mo/
      volume_number: 1
      total_pages: 134
      base_file: v001.txt
